// Code generated by goctl. DO NOT EDIT.
package types

type ShortenReq struct {
	Release string `form:"release"`
	Name    string `form:"name"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}
